
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class add_salary_record extends javax.swing.JFrame {

    /**
     * Creates new form add_salary_record
     */
    public add_salary_record() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(828, 535));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("ADD NEW SALARY RECORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(217, 27, 497, 48);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Employee no  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(49, 136, 110, 19);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(164, 125, 163, 42);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Basic Salary  ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(49, 216, 110, 19);
        getContentPane().add(t2);
        t2.setBounds(164, 205, 163, 42);
        getContentPane().add(t3);
        t3.setBounds(164, 296, 163, 42);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("PF");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(49, 307, 50, 19);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("CCA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(49, 392, 70, 19);
        getContentPane().add(t4);
        t4.setBounds(164, 381, 163, 42);
        getContentPane().add(t6);
        t6.setBounds(575, 125, 163, 42);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("DA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(474, 136, 60, 19);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Gross");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(474, 216, 70, 19);
        getContentPane().add(t7);
        t7.setBounds(570, 205, 163, 42);
        getContentPane().add(t8);
        t8.setBounds(572, 296, 163, 42);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("IT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(474, 307, 50, 19);
        getContentPane().add(t9);
        t9.setBounds(575, 381, 163, 42);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("NET");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(474, 392, 60, 19);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("HRA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(52, 486, 70, 19);
        getContentPane().add(t5);
        t5.setBounds(164, 475, 163, 42);

        b1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        b1.setText("SAVE");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(443, 476, 96, 39);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(544, 555, 96, 39);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("NEW NETRY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(612, 476, 126, 39);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office4.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 830, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
    try{
    Class.forName("java.sql.DriverManager");
    java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salarymanagement","root","");
  String empno,sql;
    double bassal,pf,cca,hra,da,gross,it,net;
    empno=t1.getText();
     bassal=Double.parseDouble(t2.getText());
    
    if(empno.equals(""))
    {
        JOptionPane.showMessageDialog(null,"PLEASE CROSS-CHECK THE ENTERIES");
    }
    else
    {
      Double bas=bassal;
      pf=0.12*bas;
      cca=1000;
      if(bas>=20000)
      {
          hra=4250;
      }
      else if(bas>=15000)
      {
          hra=4000;
      }
      else if(bas>=10000)
      {
          hra=3750;
      }
      else
      {
       hra=3500;   
      }
    if(bas>=20000)
    {
        da=2100;
    }
    else if(bas>=10000)
      {
          da=1800;
      }
    else
      {
          da=1500;
      }
    gross=bas+cca+hra+da;
    if(gross>=25000)
    {
        it=0.06*gross;
    }
    else if(gross>=20000)
    {
        it=0.04*gross;
    }
    else if(gross>=15000)
    {
        it=0.02*gross;
    }
    else
    {
        it=0.01*gross;
    }
    net=gross-pf-it;
    t3.setText(Double.toString(pf));
    t4.setText(Double.toString(cca));
    t5.setText(Double.toString(hra));
    t6.setText(Double.toString(da));
    t7.setText(Double.toString(gross));
    t8.setText(Double.toString(it));
    t9.setText(Double.toString(net));
    sql="insert into salary values("+empno+",'"+bas+"','"+pf+"','"+cca+"','"+hra+"','"+da+"','"+gross+"','"+it+"','"+net+"')";
    Statement st=con.createStatement();
    st.executeUpdate(sql);
    JOptionPane.showMessageDialog(null,"Record has been SAVED");
    t1.setEditable(false);
    t2.setEditable(false);
    t3.setEditable(false);
    t4.setEditable(false);
    t5.setEditable(false);
    t6.setEditable(false);
    t7.setEditable(false);
    t8.setEditable(false);
    t9.setEditable(false);
    b1.setVisible(false);   
    }  
    
}
catch(Exception e)
{
    
    JOptionPane.showMessageDialog(this,"Error :"+e);
    
}
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
t1.setText("");
t2.setText("");
t3.setText("");
t4.setText("");
t5.setText("");
t6.setText("");
t7.setText("");
t8.setText("");
t9.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  dispose();
input_screen i = new input_screen();
    i.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_salary_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_salary_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_salary_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_salary_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new add_salary_record().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
