
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class adda_new_record extends javax.swing.JFrame {

    /**
     * Creates new form adda_new_record
     */
    public adda_new_record() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        T8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        T9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 153));
        jLabel1.setText("Add A New Record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 520, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Employee Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 159, 38);
        getContentPane().add(T1);
        T1.setBounds(210, 100, 161, 38);
        getContentPane().add(T2);
        T2.setBounds(210, 170, 161, 38);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Employee Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 159, 38);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Sex (M/F)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 240, 159, 38);
        getContentPane().add(T3);
        T3.setBounds(210, 240, 161, 38);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 310, 159, 38);
        getContentPane().add(T4);
        T4.setBounds(210, 310, 161, 38);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 380, 159, 38);
        getContentPane().add(T5);
        T5.setBounds(210, 380, 161, 38);
        getContentPane().add(T6);
        T6.setBounds(690, 100, 161, 38);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Date Of Birth(YYYY-MM-DD)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 100, 200, 38);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Date Of Join(YYYY-MM-DD)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(470, 170, 200, 38);
        getContentPane().add(T7);
        T7.setBounds(690, 170, 161, 38);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("Job");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 240, 159, 38);
        getContentPane().add(T8);
        T8.setBounds(690, 240, 161, 38);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("Department");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 310, 159, 38);
        getContentPane().add(T9);
        T9.setBounds(690, 310, 161, 38);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 370, 206, 52);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 370, 70, 52);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background4.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -6, 870, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
input_screen s = new input_screen();
s.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
    
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salarymanagement","root","");
    String empno,ename,sex,address,city,dob,doj,job,department,sql;
    empno=T1.getText();
    ename=T2.getText();
    sex=T3.getText();
    address=T4.getText();
    city=T5.getText();
    dob=T6.getText();
    doj=T7.getText();
    job=T8.getText();
    department=T9.getText();
if(empno.equals("") || ename.equals("") || sex.equals("") || address.equals("") || city.equals("") || dob.equals("") || doj.equals("") || department.equals("") )
{
JOptionPane.showMessageDialog(null,"PLEASE RECHECK THE ENTRIES");
}
  else{  sql="insert into employee values("+empno+",'"+ename+"','"+sex+"','"+address+"','"+city+"','"+dob+"','"+doj+"','"+job+"','"+department+"')";
    System.out.print(sql);
    Statement st=con.createStatement();

st.executeUpdate(sql);
JOptionPane.showMessageDialog(null,"RECORD SAVED");
input_screen s = new input_screen();
s.setVisible(true);
}}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"ERROR:"+e.getMessage());
}



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adda_new_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adda_new_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adda_new_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adda_new_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adda_new_record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
