
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kushal
 */
public class login_newuser extends javax.swing.JFrame {

    /**
     * Creates new form login_newuser
     */
    public login_newuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(850, 556));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("User_ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(136, 105, 106, 33);

        t1.requestFocus();
        t1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(274, 102, 173, 38);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("PASSWORD :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(136, 217, 106, 33);

        t6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(t6);
        t6.setBounds(651, 334, 173, 38);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("EMAIL_ID :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(535, 337, 106, 33);

        t3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(t3);
        t3.setBounds(274, 334, 173, 38);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("PIN :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(136, 337, 106, 33);

        t4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(t4);
        t4.setBounds(645, 99, 173, 38);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("NAME :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(521, 105, 106, 33);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("OFFICE_ID :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(521, 217, 106, 33);

        t5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(t5);
        t5.setBounds(645, 216, 173, 38);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("NEW USER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(371, 11, 270, 48);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("**REQUIRED WHEN YOU FORGET YOUR PASSWORD** ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 380, 470, 20);

        jButton1.setText("CLICK TO REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(371, 418, 162, 39);
        getContentPane().add(t2);
        t2.setBounds(280, 220, 160, 40);

        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 480, 80, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dreamstime_m_26059621.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-600, -20, 1450, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salarymanagement","root","");
    String a,b,c,d,e,f,sql;
    a=t1.getText();
     b=new String(t2.getPassword());
    c=t3.getText();
    d=t4.getText();
    e=t5.getText();
    f=t6.getText();
    if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || e.equals("") || f.equals("")){
        JOptionPane.showMessageDialog(null,"PLEASE FILL DETAIL CORRECT");
    }
    else{
        sql="insert into USERS values("+a+",'"+b+"',"+c+",'"+d+"',"+e+",'"+b+"')";
        System.out.println(sql);
    Statement st =con.createStatement();
    st.executeUpdate(sql);
    JOptionPane.showMessageDialog(null,"YOUR RECORD HAS BEEN SAVED");
    JOptionPane.showMessageDialog(null,"PLEASE SIGN_IN");
    log_in i = new log_in();
    i.setVisible(true);
    dispose();
    
    }
   
    
    
   
}
catch(Exception e)
{
    
    JOptionPane.showMessageDialog(null,e.getMessage());
    JOptionPane.showMessageDialog(null,"INCORRECT USER_ID AND PIN PLEASE CROSS-CHECK");
    
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
log_in w = new log_in();
w.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_newuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
