
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class update_record extends javax.swing.JFrame {

    /**
     * Creates new form update_record
     */
    public update_record() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        T6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        T9 = new javax.swing.JTextField();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        T10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(935, 655));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 153));
        jLabel1.setText("Update an Existing Employee Record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 0, 860, 60);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Employee no.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 70, 203, 43);
        getContentPane().add(T1);
        T1.setBounds(480, 70, 164, 43);

        T2.setEditable(false);
        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        getContentPane().add(T2);
        T2.setBounds(207, 223, 164, 43);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Employee no.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 230, 203, 43);

        T3.setEditable(false);
        getContentPane().add(T3);
        T3.setBounds(207, 306, 164, 43);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Employee Name.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 310, 203, 43);

        T4.setEditable(false);
        getContentPane().add(T4);
        T4.setBounds(210, 390, 164, 43);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 470, 203, 43);

        T5.setEditable(false);
        getContentPane().add(T5);
        T5.setBounds(210, 470, 164, 43);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 550, 203, 43);

        T6.setEditable(false);
        getContentPane().add(T6);
        T6.setBounds(210, 550, 164, 43);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Date of Birth(yyy/mm/dd)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(497, 223, 203, 43);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Date of Joining(YYYY/MM/DD)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(497, 306, 203, 43);

        T7.setEditable(false);
        getContentPane().add(T7);
        T7.setBounds(700, 230, 164, 43);

        T8.setEditable(false);
        getContentPane().add(T8);
        T8.setBounds(700, 310, 164, 43);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("Job");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(497, 389, 203, 43);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("Department");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(497, 480, 203, 43);

        T9.setEditable(false);
        getContentPane().add(T9);
        T9.setBounds(700, 390, 164, 43);

        b2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        b2.setText("LOAD DATA");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(283, 140, 370, 47);

        b1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        b1.setText("UPDATE");
        b1.setVisible(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(480, 550, 140, 47);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(685, 580, 110, 47);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 203, 897, 14);

        T10.setEditable(false);
        getContentPane().add(T10);
        T10.setBounds(700, 480, 164, 43);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("Sex(M/F)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 390, 203, 43);

        jLabel12.setForeground(new java.awt.Color(255, 255, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/121471.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-250, 0, 1250, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
input_screen s = new input_screen();
s.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
try{
        String empno,ename,sex,add,city,dob,doj,job,department,sql;
Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/salarymanagement","root","");
empno=T2.getText();
ename=T3.getText();
sex=T4.getText();
add=T5.getText();
city=T6.getText();
dob=T7.getText();
doj=T8.getText();
job=T9.getText();
department=T10.getText();
if(empno.equals("") || ename.equals("") || sex.equals("") || add.equals("") || city.equals("") || dob.equals("") || doj.equals("") || department.equals("") )
{
JOptionPane.showMessageDialog(null,"PLEASE RECHECK THE ENTRIES");
}
else{sql="UPDATE EMPLOYEE SET Empno="+ empno+",Ename='"+ename+"',Sex='"+sex+"',Address='"+add+"',City='"+city+"',DOB='"+dob+"',DOJ='"+doj+"',Job='"+job+"',Department='"+department+"' where Empno="+empno;
Statement st=con.createStatement();
st.executeUpdate(sql);
System.out.println(sql);
JOptionPane.showMessageDialog(null,"..DATA HAVE BEEN UPDATED..");
}
}
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());
}
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
    try{
    
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salarymanagement","root","");
    String empno,ename="",sex="",address="",city="",dob="",doj="",job="",department="",sql="";
    empno=T1.getText();
if(empno.equals(""))
{
JOptionPane.showMessageDialog(null,"PLEASE ENTER THE EMPLOYEE_ID");
T1.requestFocus();
}
  else 
    sql="Select * from Employee where Empno="+empno;
    System.out.println(sql);
    Statement st=con.createStatement();
ResultSet rs = st.executeQuery(sql);
    if(!rs.next()){
JOptionPane.showMessageDialog(null,"..Entered Employee Number DOES NOT EXIST....");
T1.requestFocus();
}
else{b1.setVisible(true);
T1.setEditable(false);
T2.setEditable(false);
T3.setEditable(true);
T4.setEditable(true);
T5.setEditable(true);
T6.setEditable(true);
T7.setEditable(true);
T8.setEditable(true);
T9.setEditable(true);
T10.setEditable(true);

b2.setEnabled(false);
        
T2.setText(rs.getString("empno"));
T3.setText(rs.getString("ename"));
T4.setText(rs.getString("sex"));
T5.setText(rs.getString("address"));
T6.setText(rs.getString("city"));
T7.setText(rs.getString("DOB"));
T8.setText(rs.getString("DOJ"));
T9.setText(rs.getString("Job"));
T10.setText(rs.getString("Department"));
 JOptionPane.showMessageDialog(null,"..Employee DETAILS LOADED....");
JOptionPane.showMessageDialog(null,"**PLAESE UPDATE THE DETAILS**");



    }}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"ERROR:"+e.getMessage());
}    
    }//GEN-LAST:event_b2ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    //private Connection DriverManager(String jdbcmysqllocalhost3306salarymanagement, String root, String string) {
   //     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
