import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Objects;
import javax.swing.JOptionPane;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kushal
 */
public class UPDATE_SALARY_RECORD extends javax.swing.JFrame {

    /**
     * Creates new form UPDATE_SALARY_RECORD
     */
    public UPDATE_SALARY_RECORD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        b2 = new javax.swing.JButton();
        T2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        T6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        T10 = new javax.swing.JTextField();
        T9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee no.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 20, 203, 43);
        getContentPane().add(T1);
        T1.setBounds(460, 20, 164, 43);

        b2.setText("LOAD DATA");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(380, 90, 183, 47);

        T2.setEditable(false);
        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        getContentPane().add(T2);
        T2.setBounds(230, 180, 164, 43);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 204));
        jLabel3.setText("Employee no.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 203, 43);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 204));
        jLabel7.setText("DA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 190, 203, 43);

        T7.setEditable(false);
        getContentPane().add(T7);
        T7.setBounds(720, 190, 164, 43);

        T8.setEditable(false);
        getContentPane().add(T8);
        T8.setBounds(720, 270, 164, 43);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 204));
        jLabel8.setText("GROSS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 270, 203, 43);

        T3.setEditable(false);
        getContentPane().add(T3);
        T3.setBounds(230, 260, 164, 43);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 204));
        jLabel4.setText("BASIC SALARY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 260, 203, 43);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 204));
        jLabel11.setText("PF");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 340, 203, 43);

        T4.setEditable(false);
        getContentPane().add(T4);
        T4.setBounds(230, 350, 164, 43);

        T5.setEditable(false);
        getContentPane().add(T5);
        T5.setBounds(230, 430, 164, 43);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 204));
        jLabel5.setText("CCA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 430, 203, 43);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 204));
        jLabel6.setText("HRA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 510, 203, 43);

        T6.setEditable(false);
        getContentPane().add(T6);
        T6.setBounds(230, 510, 164, 43);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 204));
        jLabel10.setText("NET");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(570, 440, 203, 43);

        T10.setEditable(false);
        getContentPane().add(T10);
        T10.setBounds(720, 440, 164, 43);

        T9.setEditable(false);
        getContentPane().add(T9);
        T9.setBounds(720, 350, 164, 43);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 204));
        jLabel9.setText("IT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(580, 350, 203, 43);

        b1.setText("UPDATE");
        b1.setVisible(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(500, 540, 133, 47);

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(740, 540, 75, 47);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 162, 900, 10);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Celebrate-Success.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 900, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        try{

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salarymanagement","root","");
            String empno,sql="";
            empno=T1.getText();
            if(empno.equals(""))
            {
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE EMPLOYEE_ID");
                T1.requestFocus();
            }
            else
            sql="Select * from salary where Empno="+empno;
            System.out.println(sql);
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(!rs.next()){
                JOptionPane.showMessageDialog(null,"..Entered Employee Number DOES NOT EXIST....");
                T1.requestFocus();
            }
            else{b1.setVisible(true);
                T1.setEditable(false);
                T2.setEditable(true);
                T3.setEditable(true);

                b2.setEnabled(false);

                T2.setText(rs.getString("empno"));
                T3.setText(rs.getString("basic"));
                T4.setText(rs.getString("pf"));
                T5.setText(rs.getString("cca"));
                T6.setText(rs.getString("hra"));
                T7.setText(rs.getString("da"));
                T8.setText(rs.getString("gross"));
                T9.setText(rs.getString("it"));
                T10.setText(rs.getString("net"));
                JOptionPane.showMessageDialog(null,"..Employee DETAILS LOADED....");
                JOptionPane.showMessageDialog(null,"**PLAESE UPDATE THE DETAILS**");

            }}
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"ERROR:"+e.getMessage());
            }
    }//GEN-LAST:event_b2ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        try{
            String empno,sql;
            Double basicsal,pf,cca,hra,da,gross,it,net;
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/salarymanagement","root","");
            empno=T2.getText();
            basicsal=Double.parseDouble(T3.getText());
            pf=Double.parseDouble(T4.getText());
            cca=Double.parseDouble(T5.getText());
            hra=Double.parseDouble(T6.getText());
            da=Double.parseDouble(T7.getText());
            gross=Double.parseDouble(T8.getText());
            it=Double.parseDouble(T9.getText());
            net=Double.parseDouble(T10.getText());
            if(empno.equals("") || Objects.equals(basicsal, ""))
            {
                JOptionPane.showMessageDialog(null,"PLEASE RECHECK THE ENTRIES");
            }
             else
    {
      Double bas=basicsal;
      pf=0.12*bas;
      cca=1000.00;
      if(bas>=20000)
      {
          hra=4250.00;
      }
      else if(bas>=15000)
      {
          hra=4000.00;
      }
      else if(bas>=10000)
      {
          hra=3750.00;
      }
      else
      {
       hra=3500.00;   
      }
    if(bas>=20000)
    {
        da=2100.00;
    }
    else if(bas>=10000)
      {
          da=1800.00;
      }
    else
      {
          da=1500.00;
      }
    gross=bas+cca+hra+da;
    if(gross>=25000)
    {
        it=0.06*gross;
    }
    else if(gross>=20000)
    {
        it=0.04*gross;
    }
    else if(gross>=15000)
    {
        it=0.02*gross;
    }
    else
    {
        it=0.01*gross;
    }
    net=gross-pf-it;
    T4.setText(Double.toString(pf));
    T5.setText(Double.toString(cca));
    T6.setText(Double.toString(hra));
    T7.setText(Double.toString(da));
    T7.setText(Double.toString(gross));
    T8.setText(Double.toString(it));
    T10.setText(Double.toString(net));
    
   Double bassaal= Double.parseDouble(T3.getText());
  int a= Integer.parseInt(T2.getText());
                
                 sql="UPDATE salary SET Empno='"+ a+"',Basic='"+bassaal+"',pf='"+pf+"',cca='"+cca+"',hra='"+hra+"',da='"+da+"',gross='"+gross+"',it='"+it+"',net='"+net+"' where Empno="+empno;
                Statement st=con.createStatement();
                st.executeUpdate(sql);
                System.out.println(sql);
                JOptionPane.showMessageDialog(null,"..DATA HAVE BEEN UPDATED..");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        input_screen s = new input_screen();
        s.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATE_SALARY_RECORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATE_SALARY_RECORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATE_SALARY_RECORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATE_SALARY_RECORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATE_SALARY_RECORD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
