
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class VIEW_ATTENDANCE extends javax.swing.JFrame {

    /**
     * Creates new form VIEW_ATTENDANCE
     */
    public VIEW_ATTENDANCE() {
        initComponents();
               DefaultTableModel model=(DefaultTableModel)t1.getModel();
try{
    Class.forName("java.sql.DriverManager");
    java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salarymanagement","root","");
    Statement st=con.createStatement();
    String sql="Select * from ATTENDANCE";
    ResultSet rs = st.executeQuery(sql);
    int row = model.getRowCount();
    if(row>0){
        for(int i=0;i<row;i++){
            model.removeRow(0);
        }
        while(rs.next()){
            String empno,month="",year="",cl="",pl="",ml="",lwp="";
            empno=rs.getString("empno");
month=rs.getString("for_month");
year=rs.getString("year");
cl=rs.getString("cl");
pl=rs.getString("pl");
ml=rs.getString("ml");
lwp=rs.getString("lwp");
            model.addRow(new Object[]{empno,month,year,cl,pl,ml,lwp});
        }
    }if(row==0)
    {
                
        JOptionPane.showMessageDialog(this,"No Record Found");
        rs.close();
        st.close();
        con.close();
        
    }
}
catch(Exception e)
{
    
    JOptionPane.showMessageDialog(this,"Error :"+e);
    JOptionPane.showMessageDialog(null,"INCORRECT USER_ID AND PIN PLEASE CROSS-CHECK");
    
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(948, 407));
        getContentPane().setLayout(null);

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee_no.", "Employee Name", "Sex", "Address", "City", "Date-of-Birth", "Date-of-Joining", "Job", "Department"
            }
        ));
        t1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                t1MouseDragged(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 946, 120);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("VIEW ATTENDANCE DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 890, 57);

        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 320, 116, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/121426.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 950, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseDragged

    }//GEN-LAST:event_t1MouseDragged

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed

    }//GEN-LAST:event_t1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int a=JOptionPane.showConfirmDialog(this,"Are you sure You want To exit");
        if(a==JOptionPane.YES_OPTION)
        {
            dispose();
            input_screen s = new input_screen();
            s.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIEW_ATTENDANCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIEW_ATTENDANCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIEW_ATTENDANCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIEW_ATTENDANCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIEW_ATTENDANCE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t1;
    // End of variables declaration//GEN-END:variables
}
